// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoqUuxxj5IvaQ-8_SBHBPF_efFwMNAPzs',
    appId: '1:955658374124:web:226bd48c9dbf5717880ec9',
    messagingSenderId: '955658374124',
    projectId: 'medicalapp-de445',
    authDomain: 'medicalapp-de445.firebaseapp.com',
    storageBucket: 'medicalapp-de445.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcc7l00gYmaHtk8QWWmAlqoo1Rx904zVY',
    appId: '1:955658374124:android:bc55efe4f48b741b880ec9',
    messagingSenderId: '955658374124',
    projectId: 'medicalapp-de445',
    storageBucket: 'medicalapp-de445.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_GNjVLt-mI6wV5jiN4wbM6KZmL-aBU8o',
    appId: '1:955658374124:ios:3f0458a198cd6d14880ec9',
    messagingSenderId: '955658374124',
    projectId: 'medicalapp-de445',
    storageBucket: 'medicalapp-de445.appspot.com',
    iosBundleId: 'com.example.medical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_GNjVLt-mI6wV5jiN4wbM6KZmL-aBU8o',
    appId: '1:955658374124:ios:3f0458a198cd6d14880ec9',
    messagingSenderId: '955658374124',
    projectId: 'medicalapp-de445',
    storageBucket: 'medicalapp-de445.appspot.com',
    iosBundleId: 'com.example.medical',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoqUuxxj5IvaQ-8_SBHBPF_efFwMNAPzs',
    appId: '1:955658374124:web:d12dd5dd0be2baec880ec9',
    messagingSenderId: '955658374124',
    projectId: 'medicalapp-de445',
    authDomain: 'medicalapp-de445.firebaseapp.com',
    storageBucket: 'medicalapp-de445.appspot.com',
  );
}
